# Site Settings
locale: "en-US"
title: "CS 357 Reference"
lang: "en-US"
name: "CS 357 Reference"
description: "CS 357 Reference"
url: "cs357.github.io"
baseurl: "/textbook"
repository: "cs357/textbook"
edit: false
author: "CS 357 @ UIUC Course Staff"

theme: cs357-rtd-theme

semester: sp2024
courseUrl: https://courses.engr.illinois.edu/cs357

addons:
  - github
  - gems
  - analytics

# Reading Files
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.txt
readme_index:
  with_frontmatter: true

kramdown:
  input: GFM

# Sass/SCSS
sass:
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
