# Site Settings
locale: "en-US"
title: "CS 357 Textbook"
lang: "en-US"
name: "CS 357 Textbook"
description: "CS 357 @ UIUC Textbook"
url: "cs357.cs.illinois.edu"
baseurl: "/textbook"
repository: "cs357/textbook"
edit: false
author: "CS 357 @ UIUC Course Staff"
issuesUrl: https://github.com/cs357/textbook/issues

# taken from website config
zoomLinkLargeClassroom: https://illinois.zoom.us/j/82020014275?pwd=dlBxRGY0QXFUVmZVSHU5S2oxeXBBUT09
prairielearnUrl: https://us.prairielearn.com/pl/course_instance/171058
prairietest: https://www.prairietest.org/
discordUrl: https://discord.gg/fFudKaJ2d7


theme: cs357-rtd-theme

# NOTE: the semester tag is no longer used.
# semester: fa2024
courseUrl: https://cs357.cs.illinois.edu

addons:
  - gems
  - analytics
  - "jekyll-github-metadata"

# Reading Files
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.txt
  - cs357-rtd-theme
  - _cbtf
  - vendor
readme_index:
  with_frontmatter: true

markdown: kramdown

# Sass/SCSS
sass:
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
