# Site Settings
locale: "en-US"
title: "CS 357 Textbook"
lang: "en-US"
name: "CS 357 Textbook"
description: "CS 357 @ UIUC Textbook"
url: "cs357.cs.illinois.edu"
baseurl: "/textbook"
repository: "cs357/textbook"
edit: false
author: "CS 357 @ UIUC Course Staff"
issuesUrl: https://github.com/cs357/textbook/issues

theme: cs357-rtd-theme

semester: fa2024
courseUrl: https://cs357.cs.illinois.edu

addons:
  - gems
  - analytics

# Reading Files
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.txt
  - cs357-rtd-theme
  - _cbtf
  - vendor
readme_index:
  with_frontmatter: true

markdown: kramdown

# Sass/SCSS
sass:
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
